project:
  type: website

website:
  title: "Sophie Sees Wildlife"
  navbar:
    right:
      - about.qmd
      - icon: instagram
        href: https://www.instagram.com/sophieabrea/

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css

editor: visual

